"""add bps_code to territory tables

Revision ID: 69e80489c892
Revises: 9bd56c9fd9bb
Create Date: 2026-06-27 17:38:16.648625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e80489c892'
down_revision: Union[str, Sequence[str], None] = '9bd56c9fd9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('bps_code', sa.String(length=7), nullable=False))
    op.create_unique_constraint(
        "uq_districts_bps_code",
        "districts",
        ["bps_code"],
    )
    op.add_column('provinces', sa.Column('bps_code', sa.String(length=2), nullable=False))
    op.create_unique_constraint(
        "uq_provinces_bps_code",
        "provinces",
        ["bps_code"],
    )
    op.add_column('regencies', sa.Column('bps_code', sa.String(length=4), nullable=False))
    op.alter_column('regencies', 'code',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.create_unique_constraint(
        "uq_regencies_bps_code",
        "regencies",
        ["bps_code"],
    )
    op.add_column('villages', sa.Column('bps_code', sa.String(length=10), nullable=False))
    op.create_unique_constraint(
        "uq_villages_bps_code",
        "villages",
        ["bps_code"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_villages_bps_code",
        "villages",
        type_="unique",
    )
    op.drop_column('villages', 'bps_code')
    op.drop_constraint(
        "uq_regencies_bps_code",
        "regencies",
        type_="unique",
    )
    op.alter_column('regencies', 'code',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    op.drop_column('regencies', 'bps_code')
    op.drop_constraint(
        "uq_provinces_bps_code",
        "provinces",
        type_="unique",
    )
    op.drop_column('provinces', 'bps_code')
    op.drop_constraint(
        "uq_districts_bps_code",
        "districts",
        type_="unique",
    )
    op.drop_column('districts', 'bps_code')
    # ### end Alembic commands ###
