"""remove unique province name

Revision ID: 85ae34d1c7d4
Revises: 69e80489c892
Create Date: 2026-06-27 22:33:45.675134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ae34d1c7d4'
down_revision: Union[str, Sequence[str], None] = '69e80489c892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('provinces_name_key'), 'provinces', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('provinces_name_key'), 'provinces', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
