"""increase territory code length

Revision ID: ba1154d50ff6
Revises: 85ae34d1c7d4
Create Date: 2026-06-27 22:54:17.962480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1154d50ff6'
down_revision: Union[str, Sequence[str], None] = '85ae34d1c7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('districts', 'code',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.alter_column('villages', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('villages', 'code',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('districts', 'code',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###
