"""create citizens table

Revision ID: d18efa630d9b
Revises: ba1154d50ff6
Create Date: 2026-06-28 11:11:08.055967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18efa630d9b'
down_revision: Union[str, Sequence[str], None] = 'ba1154d50ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizens',
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('village_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizens_nik'), 'citizens', ['nik'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizens_nik'), table_name='citizens')
    op.drop_table('citizens')
    # ### end Alembic commands ###
